#!/usr/bin/env bash
url=$1
fname=$2
echo "starting download"
python3 mp3_download.py $url $fname
echo "finished download"
fname="$fname.webm"
echo "file is $fname"
ffmpeg -i "${fname}" -vn -ab 128k -ar 44100 -y "${fname%.webm}.mp3"
echo "cleaning up .webm"
rm *.webm
